### ISSUE TITLE
Other flavor based installation

### ISSUE THREAD

**Issue by ashr123** [ChrisTitusTech/TitusPi#1]
Will there be an Ubuntu based installation (64 bit distro)?
Is your installation comes with the ability to play Netflix etc… (the widevine component installed on Chromium)

**Comment by ChrisTitusTech** [comment]
Possibly in the future, but ARM64 still needs a lot of work and expansion to be a feasible alternative. I imagine it will mature in about a year or two and I will definitely transition to 64-bit. You can take any of these spins and do a modification to use a 64 bit kernel and pickup some performance, however, I left this off by default as it disables a lot of hardware acceleration.
