### ISSUE TITLE
Emulation station doesn't launch

### ISSUE THREAD

**Issue by insanewolf01** [ChrisTitusTech/TitusPi#3]
When I launch emulation station it is forever stuck on the bootlogo and says loading system config.

Please help I spend 5 euro's on this really hope i can get it to work

**Comment by ChrisTitusTech** [comment]
It should just switch over when you launch emulation station through the run command I set up. I can offer a refund if you need wolf! Send me an email at contact@christitus.com 
Subject: REFUND REQUEST - emulation station probelems
I'll get that issued after you let me know your name and when you purchased it.
